### PR TITLE
Travis support.

### PR DESCRIPTION
**Pull request by ltratt**

### CODE REVIEW

**Comment by ltratt** [comment]
[Am going to run a quick couple of tests.]

**Comment by ltratt** [comment]
OK, this is ready for merging I think.

**Comment by ptersilie** [comment]
Will this automatically be running all tests or do we need a test run command for that?

**Comment by ltratt** [comment]
It does the right thing for Rust. [I did a quick test to remind myself.]

**Comment by ptersilie** [comment]
Ok. Merged.

**Pull request merged**
